_BASE_RUN: ../../pool/run/training/from_scratch_large.yaml
_BASE_MODEL: ../../pool/backbone/tada_convnext_tiny.yaml

PRETRAIN:
  ENABLE: false
TRAIN:
  ENABLE: true
  DATASET: ssv2
  BATCH_SIZE: 16
  CHECKPOINT_FILE_PATH: "/projects/tada_convnext_tiny_tpami/k400/tiny_e002/checkpoint_epoch_00100.pyth"
  CHECKPOINT_PRE_PROCESS:
    ENABLE: true
    POP_HEAD: true
TEST:
  ENABLE: true
  DATASET: ssv2
  BATCH_SIZE: 16
DATA:
  DATA_ROOT_DIR: /Something-Something-V2/videos_mp4/
  ANNO_DIR: /Something-Something-V2/labels/
  NUM_INPUT_FRAMES: 32
  SAMPLING_RATE: 2
  SAMPLING_MODE: segment_based
  TRAIN_JITTER_SCALES: [224, 340]
  TRAIN_CROP_SIZE: 224
  TEST_SCALE: 256
  TEST_CROP_SIZE: 256
PRE_DOWNLOAD:
  ENABLE: false
OSS:
  CHECKPOINT_OUTPUT_PATH: /projects/tada_convnext_tiny/ssv2/
  SECONDARY_DATA_OSS: 
    ENABLE: true
    KEY:
    SECRET:
    ENDPOINT:
    BUCKETS: []
VIDEO:
  HEAD:
    NUM_CLASSES: 174
    DROPOUT_RATE: 0.5
DATA_LOADER:
  NUM_WORKERS: 8

MODEL:
  EMA:
    ENABLE: true
    DECAY: 0.9999

AUGMENTATION:
  COLOR_AUG: true
  BRIGHTNESS: 0.4
  CONTRAST: 0.4
  SATURATION: 0.4
  HUE: 0.25
  GRAYSCALE: 0.3
  CONSISTENT: true
  SHUFFLE: true
  GRAY_FIRST: true
  IS_SPLIT: false
  USE_GPU: false
  SSV2_FLIP: true
  RATIO: [0.75, 1.333]
  MIXUP: 
    ENABLE: true
    ALPHA: 0.8
    PROB: 1.0
    MODE: batch
    SWITCH_PROB: 0.5
  CUTMIX: 
    ENABLE: true
    ALPHA: 1.0
    MINMAX: 
  RANDOM_ERASING:
    ENABLE: true
    PROB: 0.25
    MODE: pixel
    COUNT: [1, 1]
    NUM_SPLITS: 0
    AREA_RANGE: [0.02, 0.33]
    MIN_ASPECT: 0.3
  LABEL_SMOOTHING: 0.1
  AUTOAUGMENT:
    ENABLE: true
    TYPE: rand-m7-n4-mstd0.5-inc1