MODEL:
  NAME: ConvNeXt_base
VIDEO:
  BACKBONE:
    DEPTH: [3, 3, 27, 3]
    META_ARCH: ConvNeXt
    NUM_FILTERS: [128, 256, 512, 1024]
    NUM_INPUT_CHANNELS: 3
    NUM_OUT_FEATURES: 1024
    DROP_PATH: 0.5
    LARGE_SCALE_INIT_VALUE: 1e-6
    STEM:
      NAME: Base2DStem
    BRANCH:
      NAME: ConvNeXtBlock
    NONLOCAL:
      ENABLE: false
      STAGES: [5]
      MASK_ENABLE: false
  HEAD:
    NAME: BaseHead
    ACTIVATION: softmax
    DROPOUT_RATE: 0
    NUM_CLASSES:              # !!!

