MODEL:
  NAME: R3D
  SYNC_BN: false

VIDEO:
  BACKBONE:
    DEPTH: 18
    TRANSFORMATION: bottleneck
    META_ARCH: ResNet3D
    ACTIVATION: ReLU
    NUM_FILTERS: [8, 32, 64, 128, 256]
    NUM_INPUT_CHANNELS: 3
    NUM_OUT_FEATURES: 256
    KERNEL_SIZE: [
        [5, 7, 7],
        [1, 3, 3],
        [1, 3, 3],
        [1, 3, 3],
        [1, 3, 3]
    ]
    DOWNSAMPLING: [true, false, true, true, false]
    DOWNSAMPLING_TEMPORAL: [false, false, false, false, false]
    NUM_STREAMS: 1
    EXPANSION_RATIO: 4
    BRANCH:
      NAME: R3DBranch
    STEM:
      NAME: DownSampleStem
    NONLOCAL:
      ENABLE: false
      STAGES: [5]
      MASK_ENABLE: false
  HEAD:
    NAME: BaseHead
    ACTIVATION: softmax
    DROPOUT_RATE: 0
    NUM_CLASSES:              # !!!
