MODEL:
  NAME: vivit
  SYNC_BN: false
  
VIDEO:
  BACKBONE:
    META_ARCH: FactorizedTransformer
    NUM_FEATURES: 768
    NUM_OUT_FEATURES: 768
    PATCH_SIZE: 16
    TUBELET_SIZE: 2
    DEPTH: 12
    DEPTH_TEMP: 4
    NUM_HEADS: 12
    DIM_HEAD: 64
    ATTN_DROPOUT: 0.0
    FF_DROPOUT: 0.0
    DROP_PATH: 0.2
    MLP_MULT: 4
    PRE_LOGITS: false
    STEM:
      NAME: TubeletEmbeddingStem
    BRANCH:
      NAME: LocalTransformerLayer
  HEAD:
    NAME: TransformerHead
    ACTIVATION: softmax
    DROPOUT_RATE: 0
    NUM_CLASSES:              # !!!
TRAIN:
  CHECKPOINT_PRE_PROCESS:
    ENABLE: true
    POP_HEAD: true
    POS_EMBED: 
    PATCH_EMBD: central_frame