MODEL:
  NAME: TAda2D
VIDEO:
  BACKBONE:
    DEPTH: 18
    META_ARCH: ResNet3D
    NUM_FILTERS: [64, 64, 128, 256, 512]
    NUM_INPUT_CHANNELS: 3
    NUM_OUT_FEATURES: 512
    KERNEL_SIZE: [
      [1, 7, 7],
      [1, 3, 3],
      [1, 3, 3],
      [1, 3, 3],
      [1, 3, 3]
    ]
    DOWNSAMPLING: [true, true, true, true, true]
    DOWNSAMPLING_TEMPORAL: [false, false, true, true, false]
    NUM_STREAMS: 1
    EXPANSION_RATIO: 4
    INITIALIZATION: kaiming
    STEM:
      NAME: Base2DStem
    BRANCH:
      NAME: TemporalAdaptiveSpatialConvBlockCinAdaptiveWithGlobalInfoAvgPool
      POOL_KERNEL_SIZE: [3, 1, 1]
    NONLOCAL:
      ENABLE: false
      STAGES: [5]
      MASK_ENABLE: false
  HEAD:
    NAME: BaseHead
    ACTIVATION: softmax
    DROPOUT_RATE: 0
    NUM_CLASSES:              # !!!
