MODEL:
  NAME: irCSN-transformer
  SYNC_BN: false
  
VIDEO:
  BACKBONE_VERB:
    DEPTH: 152
    META_ARCH: ResNet3D
    NUM_FILTERS: [64, 256, 512, 1024, 2048]
    NUM_INPUT_CHANNELS: 3
    NUM_OUT_FEATURES: 2048
    KERNEL_SIZE: [
      [3, 7, 7],
      [3, 3, 3],
      [3, 3, 3],
      [3, 3, 3],
      [3, 3, 3]
    ]
    DOWNSAMPLING: [true, false, true, true, true]
    DOWNSAMPLING_TEMPORAL: [false, false, true, true, true]
    NUM_STREAMS: 1
    EXPANSION_RATIO: 4
    BRANCH:
      NAME: CSNBranch
    STEM:
      NAME: DownSampleStem
    NONLOCAL:
      ENABLE: false
      STAGES: [5]
      MASK_ENABLE: false
  BACKBONE_NOUN:
    META_ARCH: FactorizedTransformer
    NUM_FEATURES: 768
    NUM_OUT_FEATURES: 768
    PATCH_SIZE: 16
    TUBELET_SIZE: 2
    DEPTH: 12
    DEPTH_TEMP: 4
    NUM_HEADS: 12
    DIM_HEAD: 64
    ATTN_DROPOUT: 0.0
    FF_DROPOUT: 0.0
    DROP_PATH: 0.1
    MLP_MULT: 4
    STEM:
      NAME: TubeletEmbeddingStem
    BRANCH:
      NAME: BaseTransformerLayer
  HEAD:
    NAME: BaseHead
    ACTIVATION: softmax
    DROPOUT_RATE: 0
    NUM_CLASSES:              # !!!
TRAIN:
  CHECKPOINT_PRE_PROCESS:
    ENABLE: true
    POP_HEAD: true
    POS_EMBED: 
    PATCH_EMBD: central_frame
