MODEL:
  NAME: timesformer
  SYNC_BN: false
  
VIDEO:
  BACKBONE:
    META_ARCH: Transformer
    NUM_FEATURES: 768
    NUM_OUT_FEATURES: 768
    PATCH_SIZE: 16
    DEPTH: 12
    NUM_HEADS: 12
    DIM_HEAD: 64
    ATTN_DROPOUT: 0.0
    FF_DROPOUT: 0.0
    DROP_PATH: 0.1
    MLP_MULT: 4
    STEM:
      NAME: PatchEmbedStem
    BRANCH:
      NAME: BaseTransformerLayer
    NONLOCAL:
      ENABLE: false
      STAGES: [5]
      MASK_ENABLE: false
    PRE_LOGITS: true
  HEAD:
    NAME: TransformerHead
    ACTIVATION: softmax
    DROPOUT_RATE: 0
    NUM_CLASSES:              # !!!
    PRE_LOGITS: false