MODEL:
  NAME: vivit
  SYNC_BN: false
  
VIDEO:
  BACKBONE:
    META_ARCH: PoolTransformer
    NUM_FEATURES: 384
    NUM_OUT_FEATURES: 384
    PATCH_SIZE: 16
    TUBELET_SIZE: 2
    DEPTH: 12
    DEPTH_TEMP: 4
    NUM_HEADS: 12
    DIM_HEAD: 64
    ATTN_DROPOUT: 0.0
    FF_DROPOUT: 0.0
    DROP_PATH: 0.1
    MLP_MULT: 4
    POOL_SIZE: 3
    LAYER_SCALE:
      ENABLE: true
      INIT_VALUE: 1e-5
    STEM:
      NAME: TubeletEmbeddingStem
    BRANCH:
      NAME: PoolTransformerLayer
  HEAD:
    NAME: TransformerHeadPool
    ACTIVATION: softmax
    DROPOUT_RATE: 0
    NUM_CLASSES:              # !!!
    PRE_LOGITS: false
TRAIN:
  CHECKPOINT_PRE_PROCESS:
    ENABLE: true
    POP_HEAD: true
    POS_EMBED: 
    PATCH_EMBD: central_frame