_BASE: ../ft_vit_video_large_ssv2.yaml
AGENT: 
  NAME: MaskAgentSeq
  AGENT_NET_NAME: CellRunningMaskAgent
  MASK_TEMPORAL_SHUFFLE: true
  MASK_SPATIAL_REPEAT: true

OPTIMIZER:
  BASE_LR: 0.00025
  LAYER_LRDECAY:
    ENABLE: true
    DECAY_WEIGHT: 0.75

TRAIN:
  BATCH_SIZE: 2
  CHECKPOINT_FILE_PATH: "checkpoints/video-mae-vit-large-k400-transferrd.pth"
  FINE_TUNE: true
  MIXED_PRECISION: true
  ENABLE: true
  CHECKPOINT_PRE_PROCESS:
    ENABLE: false
  MAE:
    MAE_LOSS_WEIGHT: 0.1
    NORMLIZE_TARGET: true
    MASK_STRIDE: [1, 1, 1]
    MASK_RATIO: 0.5

OSS:
  CHECKPOINT_OUTPUT_PATH: /model/cpkt/projects/cont_learn/mae/ssv2/vit_video_large/vit_large_50%/

DATA:
  TRAIN_JITTER_SCALES: [0.08, 1.0]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
MODEL:
  NAME: MaeVitVideoModelWithClsVideoMAEBridgingClassifier

VIDEO:
  BACKBONE:
    DROP_PATH: 0.2
  HEAD:
    NAME: PretrainVisionTransformerDecoder
    CLS_NAME: TransformerBridgingClsHead
    DROPOUT_RATE: 0.1
    CLS_DECODER:
      NUM_FEATURES: 512
      NUM_HEADS: 4
      DROP_PATH: 0.
      DEPTH: 2
      DROP_OUT: 0.1
      ATTN_DROP_OUT: 0.0
      FFN_DROP_OUT: 0.0
    DECODER:
      NAME: BaseTransformerLayer
      NUM_FEATURES: 512
      DROP_PATH: 0.
      DEPTH: 12
      NUM_HEADS: 8

AUGMENTATION:
  COLOR_AUG: false
  BRIGHTNESS: 0.4
  CONTRAST: 0.4
  SATURATION: 0.4
  HUE: 0.25
  GRAYSCALE: 0.3
  CONSISTENT: true
  SHUFFLE: true
  GRAY_FIRST: true
  IS_SPLIT: false
  USE_GPU: false
  SSV2_FLIP: true
  RATIO: [0.75, 1.333]
  MIXUP: 
    ENABLE: true
    ALPHA: 0.8
    PROB: 1.0
    MODE: batch
    SWITCH_PROB: 0.5
  CUTMIX: 
    ENABLE: true
    ALPHA: 1.0
    MINMAX: 
  RANDOM_ERASING:
    ENABLE: true
    PROB: 0.25
    MODE: pixel
    COUNT: [1, 1]
    NUM_SPLITS: 1
    AREA_RANGE: [0.02, 0.33]
    MIN_ASPECT: 0.3
  LABEL_SMOOTHING: 0.1
  AUTOAUGMENT:
    ENABLE: true
    BEFORE_CROP: true
    TYPE: rand-m9-mstd0.5-inc1
  BATCH_AUG:
    ENABLE: false
    NUM_CLIPS_PER_VIDEO: 2
MULTI_CARD: true
