_BASE_RUN: ../../pool/run/training/from_scratch_large.yaml
_BASE_MODEL: ../../pool/backbone/vit_video_large.yaml

PRETRAIN:
  ENABLE: false
TRAIN:
  ENABLE: true
  DATASET: ssv2
  BATCH_SIZE: 16
  CHECKPOINT_FILE_PATH: ""          # !!@2
  NUM_FOLDS: 10
  CHECKPOINT_PERIOD: 10
  EVAL_PERIOD: 10
TEST:
  ENABLE: true
  DATASET: ssv2
  BATCH_SIZE: 16
DATA:
  DATA_ROOT_DIR: /path/to/Something-Something-V2/videos_mp4/
  ANNO_DIR: /path/to/Something-Something-V2/labels/
  DATA_ROOT_POOL: []
  SAMPLING_RATE: 2 # from e002
  NUM_INPUT_FRAMES: 16
  SAMPLING_MODE: segment_based
PRE_DOWNLOAD:
  ENABLE: false
OSS:
  ENABLE: false
  KEY:
  SECRET:   
  LOADER_BUCKET:
  ENDPOINT:
  MODEL_BUCKET:
  CHECKPOINT_OUTPUT_PATH:                   # !!@7
  SECONDARY_DATA_OSS: 
    ENABLE: false
    KEY:
    SECRET:
    ENDPOINT:
    BUCKETS: []
VIDEO:
  BACKBONE:
    USE_CLS_TOKEN: false
    POS_EMBD_LEARNABLE: false
    DROP_PATH: 0.1
  HEAD:
    NUM_CLASSES: 174
    DROPOUT_RATE: 0.

OPTIMIZER:
  BASE_LR: 0.0005
  MIN_LR: 1e-6
  ADJUST_LR: false
  LR_POLICY: cosine
  MAX_EPOCH: 40
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  WARMUP_EPOCHS: 5
  WARMUP_START_LR: 1e-6
  OPTIM_METHOD: adamw
  DAMPENING: 0.0
  NESTEROV: true
  HEAD_LRMULT: 1
  LAYER_LRDECAY:
    ENABLE: true
    DECAY_WEIGHT: 0.65

AUGMENTATION:
  COLOR_AUG: false
  BRIGHTNESS: 0.4
  CONTRAST: 0.4
  SATURATION: 0.4
  HUE: 0.25
  GRAYSCALE: 0.3
  CONSISTENT: true
  SHUFFLE: true
  GRAY_FIRST: true
  IS_SPLIT: false
  USE_GPU: false
  RATIO: [0.75, 1.333]
  MIXUP: 
    ENABLE: true
    ALPHA: 0.8
    PROB: 1.0
    MODE: batch
    SWITCH_PROB: 0.5
  CUTMIX: 
    ENABLE: true
    ALPHA: 1.0
    MINMAX: 
  RANDOM_ERASING:
    ENABLE: true
    PROB: 0.25
    MODE: pixel
    COUNT: [1, 1]
    NUM_SPLITS: 1
    AREA_RANGE: [0.02, 0.33]
    MIN_ASPECT: 0.3
  LABEL_SMOOTHING: 0.1
  AUTOAUGMENT:
    ENABLE: true
    BEFORE_CROP: true
    TYPE: rand-m7-n4-mstd0.5-inc1
  BATCH_AUG:
    ENABLE: false
    NUM_CLIPS_PER_VIDEO: 2

LOG_PERIOD: 50
DATA_LOADER:
  NUM_WORKERS: 8